In [7]:
import numpy as np
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list)
result = arr * 4
print(result)

mean_val = np.mean(arr)
print(mean_val)

median_val = np.median(arr)
print(median_val)

std_dev = np.std(arr)
print(std_dev)

min_val = np.min(arr)
print(min_val)

max_val = np.max(arr)
print(max_val)

new_arr = arr[arr>20]
print(new_arr)

[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
4
50
[27 31 50 39 35]


In [30]:
import numpy as np
matrix = [
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
]   

np_matrix = np.array(matrix)
print("shape:", np_matrix.shape)
print("number of rows:", np_matrix.shape[0])
print("number of columns:", np_matrix.shape[1])

print("third column:", np_matrix[:, 2])
print("second row:", np_matrix[1, :])
print("multipled matrix:", np_matrix * 2)
print("mean of each column:", np.mean(np_matrix, axis = 0))
print("overall mean:", np.mean(np_matrix))
print("min of each column:", np.min(np_matrix, axis = 0))
print("max of each column:", np.max(np_matrix, axis = 0))

flattened = np_matrix.flatten()
print(flattened) #it got flattened down into one column
print("new shape:", flattened.shape)
min_index = np.argmin(flattened)
print(min_index)
max_index = np.argmax(flattened)
print(max_index)
min_coords = np.unravel_index(min_index, np_matrix.shape)
print(min_coords)
max_coords = np.unravel_index(max_index, np_matrix.shape)
print(max_coords)
greater_than_15 = np_matrix[np_matrix>15]
print("values greater than 15:", greater_than_15)
sorted_matrix = np.sort(np_matrix, axis = 1)
print("sorted matrix:", sorted_matrix)

shape: (3, 4)
number of rows: 3
number of columns: 4
third column: [17 14 19]
second row: [ 8 21 14  3]
multipled matrix: [[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
mean of each column: [ 6.33333333 15.33333333 16.66666667  7.66666667]
overall mean: 11.5
min of each column: [ 5 12 14  3]
max of each column: [ 8 21 19 11]
[ 5 12 17  9  8 21 14  3  6 13 19 11]
new shape: (12,)
7
5
(np.int64(1), np.int64(3))
(np.int64(1), np.int64(1))
values greater than 15: [17 21 19]
sorted matrix: [[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [48]:
import numpy as np

arr = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])

def get_prime_rows(arr):
    def is_prime(n):
        if n<2:
            return False
        for i in range(2, int(n**0.5) + 1):
            if n % i == 0:
                return False
        return True
    v_is_prime = np.vectorize(is_prime)
    prime_mask = v_is_prime(arr)
    return arr[np.any(prime_mask, axis=1)]
print(get_prime_rows(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [50]:
import numpy as np
def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[::2, ::2] = 1 #even rows, even cols
    board [1::2, 1::2] = 1 #odd rows, odd cols
    return board

print(checkerboard())

def reverse_checkerboard(): 
    return 1 - checkerboard()
print(reverse_checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [54]:
import numpy as np

def expansion(universe, n):
    spaces = ' ' * n
    return np.array([spaces.join(word) for word in universe])

#example
universe = np.array(['galaxy', 'clusters'])
print(expansion(universe, 1))

['g a l a x y' 'c l u s t e r s']


In [58]:
import numpy as np
def second_brightest(stars):
    return np.partition(stars, -2, axis=1)[:, -2]
#example
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print(second_brightest(stars))

[1889 1647 1138 1863 1592]
